config/routes.rb
Effectualproduction::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  get "inicio/index"
  match 'inicio' => 'inicio#index'
  get "ayuda/index"
   match 'ayuda' => 'ayuda#index'
   get "ayuda/items"
   match 'items' => 'ayuda#items'

  get "acerca/index" 
  get "acerca/contactenos"
  match 'acerca' => 'acerca#index'
  match 'contactenos' => 'acerca#contactenos'

  resources :usuarios

  resources :solicitudes

  resources :registrocompras

  resources :producciones

  resources :notas

  resources :estampados

  resources :disenos

  resources :datoscontactos

  resources :bordados

  root :to => 'inicio#index'

end

app/models/bordado.rb
class Bordado < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/datoscontacto.rb
class Datoscontacto < ActiveRecord::Base
  attr_accessible :apellido, :direccion, :email, :movil, :nombre, :telefono
end

app/models/diseno.rb
class Diseno < ActiveRecord::Base
  attr_accessible :color, :corte, :talla
end

app/models/estampado.rb
class Estampado < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/nota.rb
class Nota < ActiveRecord::Base
	 def self.search(search) 	
		where("items like '%#{search}%'" )
  end
  attr_accessible :items, :num_documento_recibe, :tipo, :unidad
end

app/models/produccion.rb
class Produccion < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/registrocompra.rb
class Registrocompra < ActiveRecord::Base
  attr_accessible :descripcion_producto, :valor_total, :valor_unidad
end

app/models/solicitud.rb
class Solicitud < ActiveRecord::Base
  attr_accessible :cantidad, :cliente_id, :dias_faltantes, :fecha_aprobacion, :fecha_entrega_cliente, :fecha_solicitud, :instructor_id, :producto, :resolucion, :saldo, :total, :unidades_entregadas
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	 def self.search(search) 	
		where("primnombre like '%#{search}%'" )
  end
  attr_accessible :clave, :email, :fecha_nac, :num_cedula, :primapellido, :primnombre, :secapellido, :secnombre
end

app/controllers/datoscontactos_controller.rb
class DatoscontactosController < ApplicationController
  # GET /datoscontactos
  # GET /datoscontactos.json
  def index
    @datoscontactos = Datoscontacto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @datoscontactos }
    end
  end

  # GET /datoscontactos/1
  # GET /datoscontactos/1.json
  def show
    @datoscontacto = Datoscontacto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datoscontacto }
    end
  end

  # GET /datoscontactos/new
  # GET /datoscontactos/new.json
  def new
    @datoscontacto = Datoscontacto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datoscontacto }
    end
  end

  # GET /datoscontactos/1/edit
  def edit
    @datoscontacto = Datoscontacto.find(params[:id])
  end

  # POST /datoscontactos
  # POST /datoscontactos.json
  def create
    @datoscontacto = Datoscontacto.new(params[:datoscontacto])

    respond_to do |format|
      if @datoscontacto.save
        format.html { redirect_to @datoscontacto, notice: 'Datoscontacto was successfully created.' }
        format.json { render json: @datoscontacto, status: :created, location: @datoscontacto }
      else
        format.html { render action: "new" }
        format.json { render json: @datoscontacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /datoscontactos/1
  # PUT /datoscontactos/1.json
  def update
    @datoscontacto = Datoscontacto.find(params[:id])

    respond_to do |format|
      if @datoscontacto.update_attributes(params[:datoscontacto])
        format.html { redirect_to @datoscontacto, notice: 'Datoscontacto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @datoscontacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datoscontactos/1
  # DELETE /datoscontactos/1.json
  def destroy
    @datoscontacto = Datoscontacto.find(params[:id])
    @datoscontacto.destroy

    respond_to do |format|
      format.html { redirect_to datoscontactos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/acerca_helper.rb
module AcercaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ayuda_helper.rb
module AyudaHelper
end

app/helpers/bordados_helper.rb
module BordadosHelper
end

app/helpers/datoscontactos_helper.rb
module DatoscontactosHelper
end

app/helpers/disenos_helper.rb
module DisenosHelper
end

app/helpers/estampados_helper.rb
module EstampadosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/datoscontactos/_datoscontacto.html.erb
<tr id=<%= "datoscontacto_#{datoscontacto.id}" %>>
  <td><%= link_to datoscontacto.id, edit_datoscontacto_path(datoscontacto), :remote => true %></td>
  <td><%= datoscontacto.nombre %></td>
  <td><%= datoscontacto.apellido %></td>
  <td><%= datoscontacto.direccion %></td>
  <td><%= datoscontacto.email %></td>
  <td><%= datoscontacto.movil %></td>
  <td><%= datoscontacto.telefono %></td>
  <td><%= datoscontacto.created_at %></td>

  <td>
     <%= link_to image_tag('mostrar.png', :width=>30, :title=>'Mostrar'), datoscontacto, :remote => true, :class => 'btn btn-success btn-mini' %>
    <%= link_to image_tag('edi.png', :width=>30, :title=>'Editar'), edit_datoscontacto_path(datoscontacto), :remote => true,
        :class => 'btn btn-mini btn-inverse' %>
    <%= link_to image_tag('eliminar.png', :width=>30, :title=>'Eliminar'), datoscontacto, 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/datoscontactos/_form.html.erb
<%= simple_form_for @datoscontacto, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :apellido %>
  <%= f.input :direccion %>
  <%= f.input :email %>
  <%= f.input :movil %>
  <%= f.input :nombre %>
  <%= f.input :telefono %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                datoscontactos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/datoscontactos/_show.html.erb
<%- model_class = Datoscontacto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='datoscontacto'>
  <p><%= @datoscontacto.id %></p>
  <p><%= @datoscontacto.nombre%></p>
  <p><%= @datoscontacto.apellido%></p>
  <p><%= @datoscontacto.direccion%></p>
  <p><%= @datoscontacto.email%></p>
  <p><%= @datoscontacto.movil%></p>
  <p><%= @datoscontacto.telefono%></p>
</div>

app/views/datoscontactos/create.js.erb
$('table tbody').append("<%= escape_javascript(render @datoscontacto) %>")
$.lazybox.close()

app/views/datoscontactos/destroy.js.erb
$("table tr#datoscontacto_<%= @datoscontacto.id %>").remove();

app/views/datoscontactos/edit.html.erb
<%- model_class = Datoscontacto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/datoscontactos/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/datoscontactos/index.html.erb
<%- model_class = Datoscontacto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:apellido) %></th>
      <th><%= model_class.human_attribute_name(:direccion) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:movil) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:telefono) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @datoscontactos.each do |datoscontacto| %>
      <tr>
        <td><%= link_to datoscontacto.id, datoscontacto_path(datoscontacto) %></td>
        <td><%= datoscontacto.apellido %></td>
        <td><%= datoscontacto.direccion %></td>
        <td><%= datoscontacto.email %></td>
        <td><%= datoscontacto.movil %></td>
        <td><%= datoscontacto.nombre %></td>
        <td><%= datoscontacto.telefono %></td>
        <td><%=l datoscontacto.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_datoscontacto_path(datoscontacto), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      datoscontacto_path(datoscontacto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_datoscontacto_path,
            :class => 'btn btn-primary' %>

app/views/datoscontactos/new.html.erb
<%- model_class = Datoscontacto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/datoscontactos/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/datoscontactos/show.html.erb
<%- model_class = Datoscontacto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:apellido) %>:</strong></dt>
  <dd><%= @datoscontacto.apellido %></dd>
  <dt><strong><%= model_class.human_attribute_name(:direccion) %>:</strong></dt>
  <dd><%= @datoscontacto.direccion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @datoscontacto.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:movil) %>:</strong></dt>
  <dd><%= @datoscontacto.movil %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @datoscontacto.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono) %>:</strong></dt>
  <dd><%= @datoscontacto.telefono %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              datoscontactos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_datoscontacto_path(@datoscontacto), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              datoscontacto_path(@datoscontacto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/datoscontactos/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/datoscontactos/update.js.erb
$('tr#datoscontacto_<%= @datoscontacto.id %>').replaceWith("<%= escape_javascript(render @datoscontacto) %>")
$.lazybox.close()