config/routes.rb
Effectualproduction::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  get "inicio/index"
  match 'inicio' => 'inicio#index'
  get "ayuda/index"
   match 'ayuda' => 'ayuda#index'
   get "ayuda/items"
   match 'items' => 'ayuda#items'

  get "acerca/index" 
  get "acerca/contactenos"
  match 'acerca' => 'acerca#index'
  match 'contactenos' => 'acerca#contactenos'

  resources :usuarios

  resources :solicitudes

  resources :registrocompras

  resources :producciones

  resources :notas

  resources :estampados

  resources :disenos

  resources :datoscontactos

  resources :bordados

  root :to => 'inicio#index'

end

app/models/bordado.rb
class Bordado < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/datoscontacto.rb
class Datoscontacto < ActiveRecord::Base
  attr_accessible :apellido, :direccion, :email, :movil, :nombre, :telefono
end

app/models/diseno.rb
class Diseno < ActiveRecord::Base
  attr_accessible :color, :corte, :talla
end

app/models/estampado.rb
class Estampado < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/nota.rb
class Nota < ActiveRecord::Base
	 def self.search(search) 	
		where("items like '%#{search}%'" )
  end
  attr_accessible :items, :num_documento_recibe, :tipo, :unidad
end

app/models/produccion.rb
class Produccion < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/registrocompra.rb
class Registrocompra < ActiveRecord::Base
  attr_accessible :descripcion_producto, :valor_total, :valor_unidad
end

app/models/solicitud.rb
class Solicitud < ActiveRecord::Base
  attr_accessible :cantidad, :cliente_id, :dias_faltantes, :fecha_aprobacion, :fecha_entrega_cliente, :fecha_solicitud, :instructor_id, :producto, :resolucion, :saldo, :total, :unidades_entregadas
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	 def self.search(search) 	
		where("primnombre like '%#{search}%'" )
  end
  attr_accessible :clave, :email, :fecha_nac, :num_cedula, :primapellido, :primnombre, :secapellido, :secnombre
end

app/controllers/bordados_controller.rb
class BordadosController < ApplicationController
  # GET /bordados
  # GET /bordados.json
  def index
    @bordados = Bordado.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bordados }
    end
  end

  # GET /bordados/1
  # GET /bordados/1.json
  def show
    @bordado = Bordado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bordado }
    end
  end

  # GET /bordados/new
  # GET /bordados/new.json
  def new
    @bordado = Bordado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bordado }
    end
  end

  # GET /bordados/1/edit
  def edit
    @bordado = Bordado.find(params[:id])
  end

  # POST /bordados
  # POST /bordados.json
  def create
    @bordado = Bordado.new(params[:bordado])

    respond_to do |format|
      if @bordado.save
        format.html { redirect_to @bordado, notice: 'Bordado was successfully created.' }
        format.json { render json: @bordado, status: :created, location: @bordado }
      else
        format.html { render action: "new" }
        format.json { render json: @bordado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bordados/1
  # PUT /bordados/1.json
  def update
    @bordado = Bordado.find(params[:id])

    respond_to do |format|
      if @bordado.update_attributes(params[:bordado])
        format.html { redirect_to @bordado, notice: 'Bordado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bordado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bordados/1
  # DELETE /bordados/1.json
  def destroy
    @bordado = Bordado.find(params[:id])
    @bordado.destroy

    respond_to do |format|
      format.html { redirect_to bordados_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/acerca_helper.rb
module AcercaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ayuda_helper.rb
module AyudaHelper
end

app/helpers/bordados_helper.rb
module BordadosHelper
end

app/helpers/disenos_helper.rb
module DisenosHelper
end

app/helpers/estampados_helper.rb
module EstampadosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/solicitudes_helper.rb
module SolicitudesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/bordados/_form.html.erb
<%= simple_form_for @bordado, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :fecha_envio %>
  <%= f.input :fecha_llegada %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bordados_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bordados/edit.html.erb
<%- model_class = Bordado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bordados/index.html.erb
<%- model_class = Bordado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:fecha_envio) %></th>
      <th><%= model_class.human_attribute_name(:fecha_llegada) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bordados.each do |bordado| %>
      <tr>
        <td><%= link_to bordado.id, bordado_path(bordado) %></td>
        <td><%= bordado.fecha_envio %></td>
        <td><%= bordado.fecha_llegada %></td>
        <td><%=l bordado.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bordado_path(bordado), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bordado_path(bordado),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bordado_path,
            :class => 'btn btn-primary' %>

app/views/bordados/new.html.erb
<%- model_class = Bordado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bordados/show.html.erb
<%- model_class = Bordado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:fecha_envio) %>:</strong></dt>
  <dd><%= @bordado.fecha_envio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fecha_llegada) %>:</strong></dt>
  <dd><%= @bordado.fecha_llegada %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bordados_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bordado_path(@bordado), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bordado_path(@bordado),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>