config/routes.rb
Effectualproduction::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  get "inicio/index"
  match 'inicio' => 'inicio#index'
  get "ayuda/index"
   match 'ayuda' => 'ayuda#index'
   get "ayuda/items"
   match 'items' => 'ayuda#items'

  get "acerca/index" 
  get "acerca/contactenos"
  match 'acerca' => 'acerca#index'
  match 'contactenos' => 'acerca#contactenos'

  resources :usuarios

  resources :solicitudes

  resources :registrocompras

  resources :producciones

  resources :notas

  resources :estampados

  resources :disenos

  resources :datoscontactos

  resources :bordados

  root :to => 'inicio#index'

end

app/models/bordado.rb
class Bordado < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/datoscontacto.rb
class Datoscontacto < ActiveRecord::Base
  attr_accessible :apellido, :direccion, :email, :movil, :nombre, :telefono
end

app/models/diseno.rb
class Diseno < ActiveRecord::Base
  attr_accessible :color, :corte, :talla
end

app/models/estampado.rb
class Estampado < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/nota.rb
class Nota < ActiveRecord::Base
	 def self.search(search) 	
		where("items like '%#{search}%'" )
  end
  attr_accessible :items, :num_documento_recibe, :tipo, :unidad
end

app/models/produccion.rb
class Produccion < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/registrocompra.rb
class Registrocompra < ActiveRecord::Base
  attr_accessible :descripcion_producto, :valor_total, :valor_unidad
end

app/models/solicitud.rb
class Solicitud < ActiveRecord::Base
  attr_accessible :cantidad, :cliente_id, :dias_faltantes, :fecha_aprobacion, :fecha_entrega_cliente, :fecha_solicitud, :instructor_id, :producto, :resolucion, :saldo, :total, :unidades_entregadas
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	 def self.search(search) 	
		where("primnombre like '%#{search}%'" )
  end
  attr_accessible :clave, :email, :fecha_nac, :num_cedula, :primapellido, :primnombre, :secapellido, :secnombre
end

app/controllers/registrocompras_controller.rb
class RegistrocomprasController < ApplicationController

  def index
    @registrocompras = Registrocompra.all 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @registrocompras }
    end
  end

  def show
      @registrocompra = Registrocompra.find(params[:id])
  end

  def new
      @registrocompra = Registrocompra.new
  end

  def edit
      @registrocompra = Registrocompra.find(params[:id])
  end

  def create
      @registrocompra = Registrocompra.new(params[:registrocompra])
      render :action => :new unless @registrocompra.save
  end

  def update
      @registrocompra = Registrocompra.find(params[:id])
      render :action => :edit unless @registrocompra.update_attributes(params[:registrocompra])
  end

  def destroy
      @registrocompra = Registrocompra.find(params[:id])
      @registrocompra.destroy
  end
  
end

app/helpers/acerca_helper.rb
module AcercaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ayuda_helper.rb
module AyudaHelper
end

app/helpers/bordados_helper.rb
module BordadosHelper
end

app/helpers/disenos_helper.rb
module DisenosHelper
end

app/helpers/estampados_helper.rb
module EstampadosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/helpers/registrocompras_helper.rb
module RegistrocomprasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/registrocompras/_form.html.erb
<%= simple_form_for(@registrocompra, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.input :descripcion_producto, :label => "Descripcion del producto",  :required => true %>
  <%= f.input :valor_total, :label => "Valor total",  :required => true %>
  <%= f.input :valor_unidad, :label => "Valor unidad",  :required => true %>
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <%= link_to 'Atras', registrocompras_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/registrocompras/_registrocompra.html.erb
<tr id=<%= "registrocompra_#{registrocompra.id}" %>>
  <td><%= link_to registrocompra.id, edit_registrocompra_path(registrocompra), :remote => true %></td>
  <td><%= registrocompra.descripcion_producto %></td>
  <td><%= registrocompra.valor_total %></td>
  <td><%= registrocompra. valor_unidad %></td>
  <td><%= registrocompra.created_at %></td>

  <td>
    <%= link_to 'Mostrar', registrocompra, :remote => true, :class => 'btn btn-mini' %>
    <%= link_to 'Editar', edit_registrocompra_path(registrocompra), :remote => true,
        :class => 'btn btn-mini' %>
    <%= link_to 'Eliminar', registrocompra, 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/registrocompras/_show.html.erb
<%- model_class = Registrocompra -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='registrocompra'>
  <p><%= @registrocompra.id %></p>
  <p><%= @registrocompra.descripcion_producto%></p>
  <p><%= @registrocompra.valor_total%></p>
  <p><%= @registrocompra.valor_unidad%></p>
</div>

app/views/registrocompras/create.js.erb
$('table tbody').append("<%= escape_javascript(render @registrocompra) %>")
$.lazybox.close()

app/views/registrocompras/destroy.js.erb
$("table tr#registrocompra_<%= @registrocompra.id %>").remove();

app/views/registrocompras/index.html.erb
<%- model_class = Registrocompra -%> 
<div class="page-header">
<h1>Registro De Compras</h1>
</div>
<div class="well" id="tablas">

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>Descripcion Del Producto</th>
      <th>Valor Total</th>
      <th>Valor Unidad</th>
      <th>Fecha de Creacion</th>
    </tr>
  </thead>
  <tbody>
     <%= render @registrocompras %>
  </tbody>
</table>
</div>
<%= link_to 'Nuevo Registro', new_registrocompra_path, :remote => true, :class => 'btn btn-primary' %>

app/views/registrocompras/update.js.erb
$('tr#registrocompra_<%= @registrocompra.id %>').replaceWith("<%= escape_javascript(render @registrocompra) %>")
$.lazybox.close()