config/routes.rb
Effectualproduction::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  get "inicio/index"
  match 'inicio' => 'inicio#index'
  get "ayuda/index"
   match 'ayuda' => 'ayuda#index'
   get "ayuda/items"
   match 'items' => 'ayuda#items'

  get "acerca/index" 
  get "acerca/contactenos"
  match 'acerca' => 'acerca#index'
  match 'contactenos' => 'acerca#contactenos'

  resources :usuarios

  resources :solicitudes

  resources :registrocompras

  resources :producciones

  resources :notas

  resources :estampados

  resources :disenos

  resources :datoscontactos

  resources :bordados

  root :to => 'inicio#index'

end

app/models/bordado.rb
class Bordado < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/datoscontacto.rb
class Datoscontacto < ActiveRecord::Base
  attr_accessible :apellido, :direccion, :email, :movil, :nombre, :telefono
end

app/models/diseno.rb
class Diseno < ActiveRecord::Base
  attr_accessible :color, :corte, :talla
end

app/models/estampado.rb
class Estampado < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/nota.rb
class Nota < ActiveRecord::Base
	 def self.search(search) 	
		where("items like '%#{search}%'" )
  end
  attr_accessible :items, :num_documento_recibe, :tipo, :unidad
end

app/models/produccion.rb
class Produccion < ActiveRecord::Base
  attr_accessible :fecha_envio, :fecha_llegada
end

app/models/registrocompra.rb
class Registrocompra < ActiveRecord::Base
  attr_accessible :descripcion_producto, :valor_total, :valor_unidad
end

app/models/solicitud.rb
class Solicitud < ActiveRecord::Base
  attr_accessible :cantidad, :cliente_id, :dias_faltantes, :fecha_aprobacion, :fecha_entrega_cliente, :fecha_solicitud, :instructor_id, :producto, :resolucion, :saldo, :total, :unidades_entregadas
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	 def self.search(search) 	
		where("primnombre like '%#{search}%'" )
  end
  attr_accessible :clave, :email, :fecha_nac, :num_cedula, :primapellido, :primnombre, :secapellido, :secnombre
end

app/controllers/notas_controller.rb
class NotasController < ApplicationController

  def index
    @notas = Nota.search(params[:search]).page(params[:page]).per_page(3)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notas } 
    end
  end

  def show
      @nota = Nota.find(params[:id])
  end

  def new
      @nota = Nota.new
  end

  def edit
      @nota = Nota.find(params[:id])
  end

  def create
      @nota = Nota.new(params[:nota])
      render :action => :new unless @nota.save
  end

  def update
      @nota = Nota.find(params[:id])
      render :action => :edit unless @nota.update_attributes(params[:nota])
  end

  def destroy
      @nota = Nota.find(params[:id])
      @nota.destroy
  end
  
end

app/helpers/acerca_helper.rb
module AcercaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ayuda_helper.rb
module AyudaHelper
end

app/helpers/bordados_helper.rb
module BordadosHelper
end

app/helpers/disenos_helper.rb
module DisenosHelper
end

app/helpers/estampados_helper.rb
module EstampadosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/solicitudes_helper.rb
module SolicitudesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/notas/_form.html.erb
<%= simple_form_for(@nota, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.input :items, :label => "Items",  :required => true %>
  <%= f.input :num_documento_recibe, :label => "Num documento recibe",  :required => true %>
  <%= f.input :unidad, :label => "Unidad",  :required => true %>
  <%= f.input :tipo, :label => "Tipo",  :required => true %>
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <%= link_to 'Atras', notas_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/notas/_nota.html.erb
<tr id=<%= "nota_#{nota.id}" %>>
  <td><%= link_to nota.id, edit_nota_path(nota), :remote => true %></td>
  <td><%= nota.items %></td>
  <td><%= nota.num_documento_recibe %></td>
  <td><%= nota.unidad %></td>
  <td><%= nota.tipo %></td>
   <td><%= nota.created_at %></td>

  <td>
     <%= link_to image_tag('mostrar.png', :width=>30, :title=>'Mostrar'), nota, :remote => true, :class => 'btn btn-success btn-mini' %>
    <%= link_to image_tag('edi.png', :width=>30, :title=>'Editar'), edit_nota_path(nota), :remote => true,
        :class => 'btn btn-mini btn-inverse' %>
    <%= link_to image_tag('eliminar.png', :width=>30, :title=>'Eliminar'), nota, 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/notas/_show.html.erb
<%- model_class = Nota -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='nota'>
  <p><%= @nota.id %></p>
  <p><%= @nota.items%></p>
  <p><%= @nota.num_documento_recibe%></p>
  <p><%= @nota.unidad%></p>
  <p><%= @nota.tipo%></p>
</div>

app/views/notas/create.js.erb
$('table tbody').append("<%= escape_javascript(render @nota) %>")
$.lazybox.close()

app/views/notas/destroy.js.erb
$("table tr#nota_<%= @nota.id %>").remove();

app/views/notas/index.html.erb
<%- model_class = Nota -%>
<div class="page-header">
<h1 id="user">Notas</h1>
</div>
<div id="bus" class="page-header">
<%= form_tag request.path, :method => 'get' do %> 
 <%= content_tag :label do %> 
 <a id="nom">Nota:</a> 
 <%= text_field_tag :search, params[:search] %> 
 <div id='botonc'>
 <%= submit_tag "Consultar", :name => nil, :id=>'botonc', :class => "btn btn-primary btn-small" %> 
 </div>
 <% end %> 
<% end %>  
</div>
<div class="well" id="tablas">
<table id="tablee" class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>Items</th>
      <th>Numero de documento (Recibe)</th>
      <th>Unidad</th>
      <th>Tipo</th>
      <th>Fecha de Creacion</th>
    </tr>
  </thead>
  <tbody>
     <%= render @notas %>
  </tbody>
</table>
</div>
<div id="nun">
<%= link_to image_tag('nuevo.png', :width=>'45px', :title=>'Nuevo'),new_nota_path, :remote => true, :class => 'btn btn-inverse' %>
</div>
 <div id="textt">
    <p align="justify">
      Esta Aplicación estará centrada en el Proceso  
    </p>
     <p align="justify">
       de control de Producción del Centro 
    </p>
     <p align="justify">
      de confección y moda (SENA), y por esta razón  
 </p>
  <p align="justify">
     constará de cuatro (4) Módulos, con
    </p>
    </div>
    <img id="notas" src="assets/notas.png">
      <div id="pag"> 
 <%= will_paginate @usuario, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
&raquo;' rescue nil %> 
</div> 

app/views/notas/update.js.erb
$('tr#nota_<%= @nota.id %>').replaceWith("<%= escape_javascript(render @nota) %>")
$.lazybox.close()